site_name: android_package_docs

theme:
  name: 'material'
  palette:
    primary: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.top
  font:
    text: Noto Sans Korean

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



repo_url: https://github.com/dongdongjae/android_package